# Generated by Django 3.1.4 on 2020-12-24 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('style', models.CharField(choices=[('embroidery floss', 'Embroidery Floss'), ('craft cord', 'Craft Cord'), ('waxed cord', 'Waxed Cord')], max_length=200)),
                ('id_number', models.IntegerField(max_length=50)),
                ('color_name', models.CharField(max_length=250)),
                ('length_owned', models.DecimalField(decimal_places=3, max_digits=50)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
