# Generated by Django 3.1.4 on 2020-12-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='id_number',
            field=models.IntegerField(),
        ),
    ]
