# Generated by Django 3.1.4 on 2020-12-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_auto_20201223_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='length_owned',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
