# Generated by Django 3.1.4 on 2020-12-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_auto_20201223_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('brand',)},
        ),
        migrations.AlterField(
            model_name='thread',
            name='style',
            field=models.CharField(choices=[('Embroidery Floss', 'Embroidery Floss'), ('Craft Cord', 'Craft Cord'), ('Waxed Cord', 'Waxed Cord')], max_length=200),
        ),
    ]
