# Generated by Django 3.1.4 on 2020-12-26 21:24

from django.conf import settings
from django.db import migrations, models
import thread.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0005_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='added_by',
            field=models.ForeignKey(on_delete=models.SET(thread.models.get_deleted_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
