# Generated by Django 3.1.4 on 2020-12-26 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0006_auto_20201226_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e4c62026-096e-4643-9ce7-2d2843e02cdc'), max_length=250, unique=True),
        ),
    ]
