# Generated by Django 3.1.4 on 2020-12-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0007_collection_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique=True),
        ),
    ]
