# Generated by Django 3.1.4 on 2020-12-28 22:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0010_auto_20201226_1411'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='collection',
            managers=[
                ('status_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
