# Generated by Django 3.1.4 on 2020-12-28 23:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0011_auto_20201228_1459'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='collection',
            managers=[
                ('public_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
