# Generated by Django 3.1.4 on 2020-12-28 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0012_auto_20201228_1503'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='collection',
            managers=[
            ],
        ),
    ]
