# Generated by Django 3.1.4 on 2021-01-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0013_auto_20201228_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=200),
        ),
        migrations.AlterField(
            model_name='thread',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='thread',
            name='style',
            field=models.CharField(choices=[('embroidery floss', 'Embroidery Floss'), ('craft cord', 'Craft Cord'), ('waxed cord', 'Waxed Cord')], max_length=200),
        ),
    ]
