# Generated by Django 3.1.4 on 2021-01-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0014_auto_20201231_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='color_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='length_owned',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
    ]
