# Generated by Django 3.1.4 on 2021-01-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0015_auto_20201231_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='length_owned',
        ),
    ]
